---
title: "data_imputing"
output: html_document
date: "2024-01-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
set.seed(42)
```

```{r}
data <- glottoget("/Users/ruidong/Desktop/Linguistics/construction/CBA_sample_recode2024_transpose.xlsx")
```

```{r}
# glottoclean_data <- glottoclean(data)
```

```{r}
data_simplify <- glottosimplify(data)
```

```{r}
data_simplify <- glottorecode_missing(data_simplify, tona = c("NA", "N/A"))
```

```{r}
colnames(data_simplify)[2:70] <- colnames(data_simplify)[2:70] |>
  sapply(
    FUN = function(idx){
      paste("X", idx, sep="")
    }
  )
```

```{r}
impute_cstrn_Z <- function(glottodata, condition_feature, condition_val, result_features, imputed_val = "Z") {
  # A function to impute the "Z" values
  result <- glottodata
  cond_ind <- which(result[, condition_feature] == condition_val)
  result[cond_ind, result_features] <- imputed_val
  result
  return(result)
}
```

```{r}
# IF 13 = N, THEN {13,1 ; 13,2 ; 13,3 ; 13,4 ; 13,5} = NA
# 
# IF 14 = N, THEN {14,1 ; 14,2 ; 14,3} = NA
# 
# IF 15 = N, THEN {15,1 ; 15,2 ; 15,3 ; 15,4} = NA

z_const <- c("13.1", "13.2", "13.3", "13.4", "13.5", "14.1", "14.2", "14.3", "15.1", "15.2", "15.3", "15.4")

z_const <- z_const |>
  sapply(
    FUN = function(idx){
      paste("X", idx, sep="")
    }
  )
```

```{r}
# data_simplify_main is 297 by 56
data_simplify_main <- data_simplify[, setdiff(colnames(data_simplify)[2:69], z_const)]
```

```{r}
data_simplify_main_factor <- data_simplify_main |>
  lapply(factor) |>
  as.data.frame()
colnames(data_simplify_main_factor) <- colnames(data_simplify_main)
```

```{r}
imp <- mice::mice(data_simplify_main_factor, method = "rf", remove_collinear = FALSE, printFlag = T)
```

```{r}
mice::md.pattern(mice::complete(imp, 1))
```

```{r}
imp.cpl <- mice::complete(imp, 1)
imp.cpl_chr <- imp.cpl |>
    apply(MARGIN = 2, as.character) |>
    as.data.frame()
#  rownames(imp.cpl_chr) <- rownames(imp.cpl)
```

```{r}
data_simplify[, colnames(imp.cpl_chr)] <- imp.cpl_chr
```

```{r}
data_imp_Z <- impute_cstrn_Z(data_simplify, condition_feature = "X13", condition_val = "N", 
                                       result_features = c("X13.1", "X13.2", "X13.3", "X13.4", "X13.5"))

data_imp_Z <- impute_cstrn_Z(data_imp_Z, condition_feature = "X14", condition_val = "N",
                                       result_features = c("X14.1", "X14.2", "X14.3"))
data_imp_Z <- impute_cstrn_Z(data_imp_Z, condition_feature = "X15", condition_val = "N", 
                                       result_features = c("X15.1", "X15.2", "X15.3", "X15.4"))
```

```{r}
mice::md.pattern(data_imp_Z)
```

```{r}
data_imp <- data_imp_Z[, 2:70] |> 
  lapply(factor) |>
  as.data.frame()
```

```{r}
imp2 <- mice::mice(data_imp, method = "rf", remove_collinear = FALSE, printFlag = T)
```

```{r}
imp2.cpl <- mice::complete(imp2, 1)
```

```{r}
data_imputed <- data_imp_Z
data_imputed[, colnames(imp2.cpl)] <- imp2.cpl 
```

```{r}
data_imputed
```






